#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


# Configurable Settings
# agent.set_env("DOCKER_ENABLE_SECURITY", data["docker_enable_security"])
# agent.set_env("SECURITY_ENABLELOGIN", data["security_enablelogin"])
agent.set_env("DOCKER_ENABLE_SECURITY", data.get("docker_enable_security",False))
agent.set_env("SECURITY_ENABLELOGIN", data.get("security_enablelogin"False))

# agent.set_env("SECURITY_INITIALLOGIN_USERNAME", data["security_initiallogin_username"])
# agent.set_env("SECURITY_INITIALLOGIN_PASSWORD", data["security_initiallogin_password"])



# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
