#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


# Configurable Settings

app_config = {
    "SYSTEM_GOOGLEVISIBILITY": "false",
    "METRICS_ENABLED": "true",
    "SYSTEM_MAXFILESIZE": "128",
    "UI_APPNAMENAVBAR": "Stirling-PDF",
    "UI_HOMEDESCRIPTION": "Stirling-PDF",
    "UI_APPNAME": "Stirling-PDF",
    "SYSTEM_DEFAULTLOCALE": "en_US",
    "DOCKER_ENABLE_SECURITY": "false",
    "SECURITY_ENABLELOGIN": "false",
    "DISABLE_ADDITIONAL_FEATURES": "false",
}
agent.write_env('app-config.env', app_config)


# just before starting systemd unit
agent.dump_env()
