#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys

# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values


# Other, Default Environments
# agent.set_env("SYSTEM_DEFAULTLOCALE",data.get("system_defaultlocale","en_US"))
# agent.set_env("UI_APPNAME",data.get("ui_appname","Stirling-PDF"))
# agent.set_env("UI_HOMEDESCRIPTION",data.get("ui_homedescription","site for Stirling-PDF"))
# agent.set_env("UI_APPNAMENAVBAR",data.get("ui_appnamenavbar","Stirling-PDF"))
# agent.set_env("SYSTEM_MAXFILESIZE",data.get("system_maxfilesize",128))
# agent.set_env("METRICS_ENABLED",data.get("metrics_enabled",False))
# agent.set_env("SYSTEM_GOOGLEVISIBILITY",data.get("system_googlevisibility",False))
agent.dump_env()
