#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["docker_enable_security"] = os.getenv("DOCKER_ENABLE_SECURITY") == "False"
config["security_enablelogin"] = os.getenv("SECURITY_ENABLELOGIN") == "False"
config["security_initiallogin_username"] = os.getenv("SECURITY_INITIIALLOGIN_USERNAME","")
config["security_initiallogin_password"] = os.getenv("SECURITY_INITIALLOGIN_PASSWORD","")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)

