#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

mkdir -vp restore
cat - >restore/stirlingpdf_restore.sh <<'EOS'
# Read dump file from standard input:
spdf_restore --no-owner --no-privileges -U stirlingpdf -d stirlingpdf
ec=$?
docker_temp_server_stop
exit $ec
EOS

# Override the image /docker-entrypoint-initdb.d contents, to restore the
# DB dump file. The container will be stopped at the end

podman run \
    --rm \
    --interactive \
    --network=none \
    --volume=./restore:/docker-entrypoint-initdb.d/:Z \
    --volume ./stirling-pdf/data:/usr/share/tesseract-ocr/5/tessdata:rw \
    --volume ./stirling-pdf/config:/configs:rw \
    --volume ./stirling-pdf/logs:/logs:rw \
    --replace --name=restore_volume \
    --env-file=volume.env \
    --env TZ=UTC \
    "${S_PDF_IMAGE}" <  stirlingpdf.spdf_dump

# If the restore is successful, clean up:
rm -rfv restore/  stirlingpdf.spdf_dump